import { apiHandler } from "@/lib/auth";
import { requireCustomer } from "@/lib/customer-auth";
import { query, tx } from "@/lib/db";
import { sendPushToRoles } from "@/lib/push";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** GET - the customer's school-run students only. */
export const GET = apiHandler(async () => {
  const session = await requireCustomer();
  const { rows } = await query(
    `SELECT s.id, s.student_code, s.student_name, s.school, s.route_id,
            s.am_pickup_time, s.pm_pickup_time, s.monthly_fee, s.amount_paid, s.balance,
            s.payment_status, s.pickup_code, s.active_status, s.start_date, s.end_date,
            v.model AS vehicle_model, v.color AS vehicle_color, v.registration AS vehicle_registration
       FROM school_student s
       LEFT JOIN vehicle v ON v.vehicle_code = s.vehicle_id
      WHERE s.customer_id = $1 AND s.deleted = FALSE
      ORDER BY s.created_at DESC LIMIT 100`,
    [session.id]
  );
  return Response.json({ data: rows });
});

/**
 * POST { student_name, guardian, guardian_phone, pickup_address, school, am_pickup_time, pm_pickup_time }
 * Creates a PENDING sign-up: staff activate it (assign route + vehicle + fee).
 * The guardian pickup code is auto-generated by the existing flow on activation;
 * here we generate one up front so the guardian always has it from day one.
 */
export const POST = apiHandler(async (req) => {
  const session = await requireCustomer();
  const body = await req.json().catch(() => ({}));

  const studentName = String(body.student_name || "").trim();
  if (!studentName) return Response.json({ error: "Child's name is required" }, { status: 400 });

  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  const code = Array.from({ length: 6 }, () => alphabet[Math.floor(Math.random() * alphabet.length)]).join("");

  const result = await tx(async (client) => {
    // unique pickup_code retry
    let code = code0(alphabet);
    for (let i = 0; i < 5; i++) {
      const e = await client.query("SELECT 1 FROM school_student WHERE pickup_code = $1", [code]);
      if (!e.rows.length) break;
      code = code0(alphabet);
    }
    const { rows } = await client.query(
      `INSERT INTO school_student(student_name, guardian, guardian_phone, pickup_address, school,
                                  am_pickup_time, pm_pickup_time, monthly_fee, amount_paid,
                                  payment_status, pickup_code, active_status, notes, source, customer_id)
       VALUES ($1,$2,$3,$4,$5,$6,$7,0,0,'Pending',$8,FALSE,$9,'portal',$10)
       RETURNING *`,
      [
        studentName,
        String(body.guardian || session.full_name).trim(),
        String(body.guardian_phone || session.phone).trim(),
        String(body.pickup_address || "").trim() || null,
        String(body.school || "").trim() || null,
        String(body.am_pickup_time || "").trim() || null,
        String(body.pm_pickup_time || "").trim() || null,
        code,
        "Signed up via customer portal - staff to set route, vehicle and monthly fee, then activate.",
        session.id,
      ]
    );
    return rows[0];
  });

  // Staff alert (fire-and-forget): office sees the school registration instantly.
  sendPushToRoles(["OPERATIONS_MANAGER", "DISPATCHER", "MANAGING_DIRECTOR"], {
    title: `New school run ${result.student_code || ""}`.trim(),
    body: "A new school transport registration was recorded.",
    url: "/app/school",
  }).catch(() => {});

  return Response.json(
    {
      data: result,
      message:
        "School run sign-up received. Keep the pickup code " +
        result.pickup_code +
        " - you will need it at pickup. Staff will confirm the route and fee.",
    },
    { status: 201 }
  );
});

function code0(alphabet) {
  return Array.from({ length: 6 }, () => alphabet[Math.floor(Math.random() * alphabet.length)]).join("");
}