// Register definitions used by the generic CRUD API and form components.
// Fields: { name, type, required, def }  (type: text|date|time|number|int|select|bool)
// `selects` reference setup_kv keys for allowed values (validated against setup_kv at write time).

export const REGISTERS = {
  bookings: {
    table: "booking",
    codeColumn: "booking_code",
    codePrefix: "EL-B",
    title: "Passenger Bookings",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER", "DISPATCHER"] },
    fields: [
      { name: "travel_date", type: "date", required: true },
      { name: "direction", type: "select", kv: "directions", required: true },
      { name: "departure_time", type: "time" },
      { name: "customer_name", type: "text", required: true },
      { name: "phone", type: "text" },
      { name: "seats", type: "int", required: true, def: 1 },
      { name: "fare_per_seat", type: "number", def: 90 },
      { name: "amount_paid", type: "number", def: 0 },
      { name: "payment_method", type: "select", kv: "payment_methods" },
      { name: "status", type: "select", kv: "booking_statuses", def: "Pending" },
      { name: "pickup_point", type: "text" },
      { name: "dropoff_point", type: "text" },
      { name: "vehicle_id", type: "vehicle" },
      { name: "booked_by", type: "text" },
      { name: "notes", type: "text", long: true },
    ],
    computed: ["passenger_revenue", "balance"],
  },
  dispatch: {
    table: "dispatch",
    codeColumn: "dispatch_code",
    codePrefix: "EL-D",
    title: "Dispatch Board",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER", "DISPATCHER"] },
    fields: [
      { name: "date", type: "date", required: true },
      { name: "departure_time", type: "time" },
      { name: "direction", type: "select", kv: "directions", required: true },
      { name: "vehicle_id", type: "vehicle" },
      { name: "driver", type: "text" },
      { name: "seats_booked", type: "int", def: 0 },
      { name: "seat_capacity", type: "int", def: 3 },
      { name: "passenger_revenue", type: "number", def: 0 },
      { name: "parcel_revenue", type: "number", def: 0 },
      { name: "decision", type: "select", kv: "dispatch_decisions", def: "Go" },
      { name: "decision_reason", type: "text" },
      { name: "scheduled_departure", type: "time" },
      { name: "actual_departure", type: "time" },
      { name: "arrival_time", type: "time" },
      { name: "on_time_status", type: "select", options: ["On time", "Late"] },
      { name: "dispatcher", type: "text" },
    ],
    computed: ["occupancy", "total_revenue"],
  },
  parcels: {
    table: "parcel",
    codeColumn: "parcel_code",
    codePrefix: "EL-P",
    title: "Parcels",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER", "DISPATCHER", "RIDER"] },
    fields: [
      { name: "booking_date", type: "date", required: true },
      { name: "sender", type: "text", required: true },
      { name: "sender_phone", type: "text" },
      { name: "recipient", type: "text", required: true },
      { name: "recipient_phone", type: "text" },
      { name: "pickup_address", type: "text" },
      { name: "delivery_address", type: "text" },
      { name: "description", type: "text" },
      { name: "declared_value", type: "number", def: 0 },
      { name: "size", type: "select", kv: "parcel_sizes", def: "Small" },
      { name: "service", type: "text" },
      { name: "intercity_charge", type: "number", def: 0 },
      { name: "pickup_charge", type: "number", def: 0 },
      { name: "delivery_charge", type: "number", def: 0 },
      { name: "amount_paid", type: "number", def: 0 },
      { name: "payment_method", type: "select", kv: "payment_methods" },
      { name: "status", type: "select", kv: "parcel_statuses", def: "Booked" },
      { name: "vehicle_id", type: "vehicle" },
      { name: "rider", type: "text" },
      { name: "proof_of_delivery", type: "text" },
      { name: "exception_notes", type: "text", long: true },
    ],
    computed: ["total_charge", "balance"],
  },
  trips: {
    table: "trip",
    codeColumn: "trip_code",
    codePrefix: "EL-T",
    title: "Trips",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER"] },
    fields: [
      { name: "date", type: "date", required: true },
      { name: "vehicle_id", type: "vehicle" },
      { name: "driver", type: "text" },
      { name: "direction", type: "select", kv: "directions" },
      { name: "start_odometer", type: "number", required: true },
      { name: "end_odometer", type: "number", required: true },
      { name: "passengers", type: "int", def: 0 },
      { name: "passenger_revenue", type: "number", def: 0 },
      { name: "parcel_revenue", type: "number", def: 0 },
      { name: "private_hire_revenue", type: "number", def: 0 },
      { name: "other_revenue", type: "number", def: 0 },
      { name: "tolls", type: "number", def: 0 },
      { name: "fuel_cost", type: "number", def: 0 },
      { name: "incident_status", type: "select", kv: "incident_statuses", def: "None" },
      { name: "notes", type: "text", long: true },
    ],
    computed: ["kilometres", "total_revenue", "maintenance_reserve", "direct_contribution", "revenue_per_km"],
  },
  fuel: {
    table: "fuel",
    codeColumn: "fuel_code",
    codePrefix: "EL-F",
    title: "Fuel Log",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER"] },
    fields: [
      { name: "date", type: "date", required: true },
      { name: "vehicle_id", type: "vehicle", required: true },
      { name: "trip_id", type: "int" },
      { name: "station", type: "text" },
      { name: "litres", type: "number", required: true },
      { name: "price_per_litre", type: "number", def: 17 },
      { name: "odometer", type: "number", required: true },
      { name: "receipt_number", type: "text" },
      { name: "approved_by", type: "text" },
      { name: "variance_note", type: "text", long: true },
    ],
    computed: ["total_fuel_cost", "km_since_prior_fuel", "litres_per_100km"],
  },
  fleet: {
    table: "vehicle",
    codeColumn: "vehicle_code",
    codePrefix: null,
    title: "Fleet",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER"] },
    fields: [
      { name: "vehicle_code", type: "text", required: true },
      { name: "type", type: "text", required: true },
      { name: "primary_role", type: "text", required: true },
      { name: "registration", type: "text" },
      { name: "model", type: "text" },
      { name: "color", type: "text" },
      { name: "opening_odometer", type: "number", def: 0 },
      { name: "current_odometer", type: "number", def: 0 },
      { name: "next_service_odometer", type: "number" },
      { name: "last_inspection", type: "date" },
      { name: "insurance_expiry", type: "date" },
      { name: "roadworthy_expiry", type: "date" },
      { name: "status", type: "select", kv: "vehicle_statuses", def: "Available" },
      { name: "open_defect", type: "text" },
      { name: "required_action", type: "text" },
      { name: "assigned_driver", type: "text" },
      { name: "seat_capacity", type: "int", def: 4 },
      { name: "rate_per_km", type: "number" },
      { name: "km_per_litre", type: "number" },
    ],
    computed: ["km_to_service"],
  },
  "private-hire": {
    table: "private_hire",
    codeColumn: "hire_code",
    codePrefix: "EL-H",
    title: "Private Hire",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER", "DISPATCHER"] },
    fields: [
      { name: "service_date", type: "date", required: true },
      { name: "customer", type: "text", required: true },
      { name: "phone", type: "text" },
      { name: "service_type", type: "select", kv: "service_types", def: "Standard seat" },
      { name: "pickup", type: "text" },
      { name: "destination", type: "text" },
      { name: "start_time", type: "time" },
      { name: "end_time", type: "time" },
      { name: "vehicle_id", type: "vehicle" },
      { name: "driver", type: "text" },
      { name: "quoted_amount", type: "number", required: true },
      { name: "amount_paid", type: "number", def: 0 },
      { name: "status", type: "select", kv: "private_hire_statuses", def: "Inquiry" },
      { name: "kilometres", type: "number", def: 0 },
      { name: "fuel_and_tolls", type: "number", def: 0 },
      { name: "notes", type: "text", long: true },
    ],
    computed: ["balance", "contribution"],
  },
  school: {
    table: "school_student",
    codeColumn: "student_code",
    codePrefix: "EL-S",
    title: "School Transport",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "OPERATIONS_MANAGER", "DISPATCHER"] },
    fields: [
      { name: "student_name", type: "text", required: true },
      { name: "guardian", type: "text" },
      { name: "guardian_phone", type: "text" },
      { name: "pickup_address", type: "text" },
      { name: "school", type: "text" },
      { name: "route_id", type: "text" },
      { name: "am_pickup_time", type: "time" },
      { name: "pm_pickup_time", type: "time" },
      { name: "monthly_fee", type: "number", required: true },
      { name: "amount_paid", type: "number", def: 0 },
      { name: "payment_status", type: "select", kv: "school_payment_statuses", def: "Pending" },
      { name: "authorized_guardian1", type: "text" },
      { name: "authorized_guardian2", type: "text" },
      { name: "vehicle_id", type: "vehicle" },
      { name: "driver", type: "text" },
      { name: "start_date", type: "date" },
      { name: "end_date", type: "date" },
      { name: "active_status", type: "bool", def: true },
      { name: "notes", type: "text", long: true },
    ],
    computed: ["balance"],
  },
  cash: {
    table: "cash_reconciliation",
    codeColumn: null,
    codePrefix: null,
    title: "Cash Reconciliation",
    roles: { read: "ANY", write: ["MANAGING_DIRECTOR", "ACCOUNTANT"] },
    fields: [
      { name: "date", type: "date", required: true },
      { name: "opening_cash", type: "number", def: 0 },
      { name: "passenger_cash", type: "number", def: 0 },
      { name: "passenger_momo", type: "number", def: 0 },
      { name: "parcel_cash", type: "number", def: 0 },
      { name: "parcel_momo", type: "number", def: 0 },
      { name: "private_hire_receipts", type: "number", def: 0 },
      { name: "school_receipts", type: "number", def: 0 },
      { name: "other_income", type: "number", def: 0 },
      { name: "refunds", type: "number", def: 0 },
      { name: "fuel_paid_cash", type: "number", def: 0 },
      { name: "other_expenses", type: "number", def: 0 },
      { name: "actual_closing_cash", type: "number", def: 0 },
      { name: "momo_expected", type: "number", def: 0 },
      { name: "momo_confirmed", type: "number", def: 0 },
      { name: "reconciled_by", type: "text" },
      { name: "notes", type: "text", long: true },
    ],
    computed: [
      "total_collections",
      "expected_closing_cash",
      "cash_variance",
      "momo_variance",
      "review_status",
    ],
  },
};

export const REGISTER_KEYS = Object.keys(REGISTERS);
