
-- ================= Driver applications (public form + CEO/HR review) =================
CREATE TABLE IF NOT EXISTS driver_application (
  id              SERIAL PRIMARY KEY,
  full_name       TEXT NOT NULL,
  phone           TEXT NOT NULL UNIQUE,
  email           TEXT,
  password_hash   TEXT NOT NULL,
  license_no      TEXT NOT NULL,
  license_expiry  DATE NOT NULL,
  ghana_card_no   TEXT NOT NULL,
  ghana_card_image  TEXT,          -- base64 data URL (JPG/PNG/WebP, 2MB cap)
  vehicle_reg_no  TEXT NOT NULL,
  vehicle_make    TEXT,
  vehicle_color   TEXT NOT NULL,
  vehicle_images  TEXT,            -- base64 data URL list separated by | | pipe
  insurance_expiry  DATE NOT NULL,
  roadworthy_expiry DATE NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','declined')),
  reviewed_by     INTEGER REFERENCES app_user(id),
  reviewed_at     TIMESTAMPTZ,
  review_note     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- When approved, a staff account is created automatically:
--   username = first-name-initial + surname, role DRIVER, must_change_password = TRUE
--   (generated by the approval API, not by SQL)
